### ISSUE TITLE
[BUG] fontWeight typed to only string, should allow number

### ISSUE THREAD

**Issue by haxxxton** [Polyconseil/flow-inlinestyle#1]
Thank you so much for this set of types!

Just found that flow was complaining at me for using a numerical `fontWeight` which the [MDN says should be supported](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight). Would be great to have that updated :)

**Comment by HenriJ** [comment]
Hi @haxxxton 
Thank you for the bug report. It is now fixed.
Have a nice one

**Comment by haxxxton** [comment]
Thanks so much, would have submitted a pull request, but wasnt sure how to use the python script :)
